-- Author: Aryan Singh
-- Project: E-Commerce Order Analytics
-- Description: SQL analysis queries ranging from basic to advanced
-- ============================================================

USE ecommerce_analytics;

-- ============================================================
--                      SECTION 1: FUNDAMENTALS
-- ============================================================


-- List all unique cities where customers are located

SELECT DISTINCT customer_city
FROM customers
ORDER BY customer_city ASC;


-- Count the number of orders placed in 2017

SELECT COUNT(order_id) AS orders_in_2017
FROM orders;


-- Find the total sales per category

SELECT DISTINCT product_category
FROM products;


-- Calculate the number of orders that were paid in installments

SELECT COUNT(order_id) AS installment_orders
FROM payments
WHERE payment_installments > 1;


-- Count the number of customers from each state

SELECT
    customer_state,
    COUNT(customer_id) AS customer_count
FROM customers
GROUP BY customer_state
ORDER BY customer_count DESC;


-- ============================================================
--                    SECTION 2: INTERMEDIATE
-- ============================================================


-- Calculate the number of orders per month in 2018

SELECT
    MONTH(order_purchase_timestamp) AS order_month,
    COUNT(order_id) AS monthly_order_count
FROM order_items
WHERE YEAR(order_purchase_timestamp) = 2018
GROUP BY MONTH(order_purchase_timestamp)
ORDER BY order_month;


-- Find the average number of products per order, group by customer city

SELECT
    c.customer_city,
    ROUND(AVG(sub.product_count), 2) AS avg_products_per_order
FROM (
    SELECT
        oi.order_id,
        oi.customer_id,
        COUNT(o.product_id) AS product_count
    FROM order_items oi
    INNER JOIN orders o ON oi.order_id = o.order_id
    GROUP BY oi.order_id, oi.customer_id
) AS sub
INNER JOIN customers c ON sub.customer_id = c.customer_id
GROUP BY c.customer_city;


-- Calculate the percentage of total revenue contributed by each product category

SELECT
    p.product_category,
    ROUND(SUM(o.price), 2) AS revenue,
    ROUND(
        SUM(o.price) * 100.0 / SUM(SUM(o.price)) OVER(), 2
    ) AS revenue_share_pct
FROM orders o
INNER JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_category;


-- Identify the correlation between product price and the number of times a product has been purchased

SELECT
    o.product_id,
    AVG(o.price) AS avg_price,
    COUNT(*) AS total_purchases
FROM orders o
GROUP BY o.product_id
ORDER BY total_purchases DESC;


-- Calculate the total revenue generated by each seller, and rank them by revenue

SELECT
    o.seller_id,
    ROUND(SUM(o.price), 2) AS seller_revenue,
    RANK() OVER (ORDER BY SUM(o.price) DESC) AS revenue_rank
FROM orders o
GROUP BY o.seller_id
ORDER BY revenue_rank;


-- ============================================================
--                      SECTION 3: ADVANCED
-- ============================================================


-- Calculate the moving average of order values for each customer over their order history

SELECT
    oi.customer_id,
    oi.order_id,
    oi.order_purchase_timestamp,
    SUM(o.price) AS order_value,
    AVG(SUM(o.price)) OVER (
        PARTITION BY oi.customer_id
        ORDER BY oi.order_purchase_timestamp
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS moving_avg
FROM order_items oi
INNER JOIN orders o ON oi.order_id = o.order_id
GROUP BY oi.customer_id, oi.order_id, oi.order_purchase_timestamp
ORDER BY oi.customer_id, oi.order_purchase_timestamp;


-- Calculate the cumulative sales per month for each year

SELECT
    YEAR(oi.order_purchase_timestamp) AS yr,
    MONTH(oi.order_purchase_timestamp) AS mo,
    SUM(o.price) AS monthly_revenue,
    SUM(SUM(o.price)) OVER (
        PARTITION BY YEAR(oi.order_purchase_timestamp)
        ORDER BY MONTH(oi.order_purchase_timestamp)
    ) AS cumulative_revenue
FROM order_items oi
INNER JOIN orders o ON oi.order_id = o.order_id
GROUP BY YEAR(oi.order_purchase_timestamp), MONTH(oi.order_purchase_timestamp)
ORDER BY yr, mo;


-- Calculate the year-over-year growth rate of total sales

WITH yearly_revenue AS (
    SELECT
        YEAR(oi.order_purchase_timestamp) AS yr,
        SUM(o.price) AS total_revenue
    FROM order_items oi
    INNER JOIN orders o ON oi.order_id = o.order_id
    GROUP BY YEAR(oi.order_purchase_timestamp)
)
SELECT
    curr.yr AS year,
    ROUND(curr.total_revenue, 2) AS current_revenue,
    ROUND(prev.total_revenue, 2) AS prior_year_revenue,
    ROUND(
        ((curr.total_revenue - prev.total_revenue) / prev.total_revenue) * 100, 2
    ) AS yoy_growth_pct
FROM yearly_revenue curr
LEFT JOIN yearly_revenue prev ON curr.yr = prev.yr + 1
ORDER BY curr.yr;


-- Calculate the retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase

WITH first_orders AS (
    SELECT customer_id, MIN(order_purchase_timestamp) AS first_order_date
    FROM order_items
    GROUP BY customer_id
),
returning_customers AS (
    SELECT DISTINCT fo.customer_id
    FROM first_orders fo
    INNER JOIN order_items oi ON fo.customer_id = oi.customer_id
    WHERE oi.order_purchase_timestamp > fo.first_order_date
      AND oi.order_purchase_timestamp <= DATE_ADD(fo.first_order_date, INTERVAL 6 MONTH)
)
SELECT
    COUNT(DISTINCT fo.customer_id) AS total_customers,
    COUNT(DISTINCT rc.customer_id) AS retained_customers,
    ROUND(
        (COUNT(DISTINCT rc.customer_id) / COUNT(DISTINCT fo.customer_id)) * 100, 2
    ) AS retention_rate_pct
FROM first_orders fo
LEFT JOIN returning_customers rc ON fo.customer_id = rc.customer_id;


-- Identify the top 3 customers who spent the most money in each year

WITH yearly_customer_spend AS (
    SELECT
        oi.customer_id,
        YEAR(oi.order_purchase_timestamp) AS yr,
        SUM(o.price) AS total_spent,
        ROW_NUMBER() OVER (
            PARTITION BY YEAR(oi.order_purchase_timestamp)
            ORDER BY SUM(o.price) DESC
        ) AS spend_rank
    FROM order_items oi
    INNER JOIN orders o ON oi.order_id = o.order_id
    GROUP BY oi.customer_id, YEAR(oi.order_purchase_timestamp)
)
SELECT yr AS year, customer_id, ROUND(total_spent, 2) AS total_spent, spend_rank
FROM yearly_customer_spend
WHERE spend_rank <= 3
ORDER BY yr, spend_rank;
